name: cd

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            # Configure git prior to git subtree add - required to fetch from origin
            - name: Configure Git
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"

            # Add the dist directory from our subtree prior to building with npm
            # - required to have most up-do-date git history prior to pushing
            - name: Add 'dist' directory from deploy branch subtree
              run: git subtree add --prefix dist origin deploy || echo "dist directory not set up - see above information"

            # Install dependencies and build to dist
            - name: Install dependencies
              run: npm install

            - name: Run Build
              run: npm run build

            # Pushing via subtree ensures that we push only the contents of the dist directory (and not the directory itself)
            # to our desired deployment branch.
            - name: Deploy to pages
              run: |
                  git add -A -f dist/.
                  git commit -m "build: PR #${{ github.event.pull_request.number }}"
                  git subtree push --prefix dist origin deploy
